// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgNdCGM2mPydD-qkBW4us6-HDQ2_QPbwg',
    appId: '1:980854500772:android:d45b1d8f43bb5256ab6531',
    messagingSenderId: '980854500772',
    projectId: 'news-app-802e3',
    storageBucket: 'news-app-802e3.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIkWFRNUMGEFIB5gSIGi7t8KQaj8BKwSg',
    appId: '1:980854500772:web:1a475b6f913f4228ab6531',
    messagingSenderId: '980854500772',
    projectId: 'news-app-802e3',
    authDomain: 'news-app-802e3.firebaseapp.com',
    storageBucket: 'news-app-802e3.appspot.com',
    measurementId: 'G-XP22SC6ZC2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtz9pifvzg8YnsTqEOQ6eu0RzJlly9eMk',
    appId: '1:980854500772:ios:44ed8420ca55bd3fab6531',
    messagingSenderId: '980854500772',
    projectId: 'news-app-802e3',
    storageBucket: 'news-app-802e3.appspot.com',
    iosBundleId: 'com.sptpra.newsApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtz9pifvzg8YnsTqEOQ6eu0RzJlly9eMk',
    appId: '1:980854500772:ios:44ed8420ca55bd3fab6531',
    messagingSenderId: '980854500772',
    projectId: 'news-app-802e3',
    storageBucket: 'news-app-802e3.appspot.com',
    iosBundleId: 'com.sptpra.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIkWFRNUMGEFIB5gSIGi7t8KQaj8BKwSg',
    appId: '1:980854500772:web:104bf9b1e79a2354ab6531',
    messagingSenderId: '980854500772',
    projectId: 'news-app-802e3',
    authDomain: 'news-app-802e3.firebaseapp.com',
    storageBucket: 'news-app-802e3.appspot.com',
    measurementId: 'G-Q31TLWJKHC',
  );

}